export enum BusinessVertical {
  ECOMMERCE = "ECOMMERCE",
  APPOINTMENTS = "APPOINTMENTS",
  RESERVATIONS = "RESERVATIONS",
  FOOD_AND_DRINK = "FOOD_AND_DRINK",
  CREATIVE = "CREATIVE",
  ADS_TARGETING = "ADS_TARGETING",
  LEAD_ADS = "LEAD_ADS",
  MEASUREMENT_AND_OPTIMIZATION = "MEASUREMENT_AND_OPTIMIZATION",
}

export enum MBEFlow {
  ADS_MINIMAL,
  CATALOG_ADS,
  CHECKBOX_PLUGIN,
  CHECKBOX_PLUGIN_MARKETING,
  COMMERCE,
  COMMERCE_OFFSITE,
  CONVERSIONS_API,
  CONVERSIONS_API_MINIMAL,
  CREATIVE,
  CREATIVE_WITH_ASSETS,
  CUSTOM_AUDIENCE,
  CUSTOMER_DATA,
  DEFAULT,
  FB_SERVICES,
  FEED,
  AR_COMMERCE,
  IG_CREATORS_AS_SELLERS,
  LEAD_ADS,
  MARKETPLACE,
  MESSENGER_CHAT,
  MESSENGER_MARKETING,
}

export enum MBECtaButtonText {
  BOOK_NOW = "Book Now",
  BUY_NOW = "Buy Now",
  RESERVE = "Reserve",
  ORDER_FOOD = "Order Food",
}

export enum PageCardSeeAllText {
  SEE_ALL = "See All",
}

export enum PageCardCtaButtonText {
  BOOK,
}

export type MBEConfig = {
  extras: MBEExtrasConfig;
};

export type MBEExtrasConfig = {
  setup: MBEExtrasSetup;
  business_config: MBEExtrasBusinessConfig;
  repeat: boolean;
};

export type MBEExtrasSetup = {
  external_business_id: string;
  timezone: string;
  currency: string;
  business_vertical: BusinessVertical;
  domain?: string;
  channel?: MBEFlow;
  business_manager_id?: string;
  ad_account_id?: string;
  page_id?: string;
  ig_profile_id?: string;
  pixel_id?: string;
  catalog_id?: string;
  flow_config: MBEFlowConfigData;
};

export type MBEExtrasBusinessConfig = {
  business: MBEBusinessPropertiesConfigData;
  messenger_chat?: MBEMessengerChatConfigData;
  catalog_feed_scheduled?: MBECatalogFeedConfigData;
  page_cta?: MBEPageCtaConfigData;
  page_card?: MBEPageCardConfigData;
  ig_cta?: MBEIGCtaConfigData;
  messenger_menu?: MBEMessengerMenuConfigData;
  thread_intent?: MBEThreadIntentConfigData;
};

export type MBEMessengerChatConfigData = {
  enabled: boolean;
  domains: string[];
};

export type MBECatalogFeedConfigData = {
  enabled: boolean;
  feed_url: string;
};

export type MBEPageCtaConfigData = {
  enabled: boolean;
  cta_button_text: MBECtaButtonText;
  cta_button_url: string;
  below_button_text: string;
};

export type MBEPageCardConfigData = {
  enabled: boolean;
  see_all_text: PageCardSeeAllText;
  see_all_url: string;
  cta_button_text: PageCardCtaButtonText;
};

export type MBEIGCtaConfigData = {
  enabled: boolean;
  cta_button_text: MBECtaButtonText;
  cta_button_url: string;
};

export type MBEMessengerMenuConfigData = {
  enabled: boolean;
  cta_button_text: MBECtaButtonText;
  cta_button_url: string;
};

export type MBEThreadIntentConfigData = {
  enabled: boolean;
  cta_button_url: string;
};

export type MBEBusinessPropertiesConfigData = {
  name: string;
};

export type MBEFlowConfigData = {
  use_minimal_onboarding?: boolean;
};

export const Timezones: string[] = [
  "Africa/Abidjan",
  "Africa/Accra",
  "Africa/Addis_Ababa",
  "Africa/Algiers",
  "Africa/Asmara",
  "Africa/Asmera",
  "Africa/Bamako",
  "Africa/Bangui",
  "Africa/Banjul",
  "Africa/Bissau",
  "Africa/Blantyre",
  "Africa/Brazzaville",
  "Africa/Bujumbura",
  "Africa/Cairo",
  "Africa/Casablanca",
  "Africa/Ceuta",
  "Africa/Conakry",
  "Africa/Dakar",
  "Africa/Dar_es_Salaam",
  "Africa/Djibouti",
  "Africa/Douala",
  "Africa/El_Aaiun",
  "Africa/Freetown",
  "Africa/Gaborone",
  "Africa/Harare",
  "Africa/Johannesburg",
  "Africa/Juba",
  "Africa/Kampala",
  "Africa/Khartoum",
  "Africa/Kigali",
  "Africa/Kinshasa",
  "Africa/Lagos",
  "Africa/Libreville",
  "Africa/Lome",
  "Africa/Luanda",
  "Africa/Lubumbashi",
  "Africa/Lusaka",
  "Africa/Malabo",
  "Africa/Maputo",
  "Africa/Maseru",
  "Africa/Mbabane",
  "Africa/Mogadishu",
  "Africa/Monrovia",
  "Africa/Nairobi",
  "Africa/Ndjamena",
  "Africa/Niamey",
  "Africa/Nouakchott",
  "Africa/Ouagadougou",
  "Africa/Porto-Novo",
  "Africa/Sao_Tome",
  "Africa/Timbuktu",
  "Africa/Tripoli",
  "Africa/Tunis",
  "Africa/Windhoek",
  "America/Adak",
  "America/Anchorage",
  "America/Anguilla",
  "America/Antigua",
  "America/Araguaina",
  "America/Argentina/Buenos_Aires",
  "America/Argentina/Catamarca",
  "America/Argentina/ComodRivadavia",
  "America/Argentina/Cordoba",
  "America/Argentina/Jujuy",
  "America/Argentina/La_Rioja",
  "America/Argentina/Mendoza",
  "America/Argentina/Rio_Gallegos",
  "America/Argentina/Salta",
  "America/Argentina/San_Juan",
  "America/Argentina/San_Luis",
  "America/Argentina/Tucuman",
  "America/Argentina/Ushuaia",
  "America/Aruba",
  "America/Asuncion",
  "America/Atikokan",
  "America/Atka",
  "America/Bahia",
  "America/Bahia_Banderas",
  "America/Barbados",
  "America/Belem",
  "America/Belize",
  "America/Blanc-Sablon",
  "America/Boa_Vista",
  "America/Bogota",
  "America/Boise",
  "America/Buenos_Aires",
  "America/Cambridge_Bay",
  "America/Campo_Grande",
  "America/Cancun",
  "America/Caracas",
  "America/Catamarca",
  "America/Cayenne",
  "America/Cayman",
  "America/Chicago",
  "America/Chihuahua",
  "America/Coral_Harbour",
  "America/Cordoba",
  "America/Costa_Rica",
  "America/Creston",
  "America/Cuiaba",
  "America/Curacao",
  "America/Danmarkshavn",
  "America/Dawson",
  "America/Dawson_Creek",
  "America/Denver",
  "America/Detroit",
  "America/Dominica",
  "America/Edmonton",
  "America/Eirunepe",
  "America/El_Salvador",
  "America/Ensenada",
  "America/Fort_Nelson",
  "America/Fort_Wayne",
  "America/Fortaleza",
  "America/Glace_Bay",
  "America/Godthab",
  "America/Goose_Bay",
  "America/Grand_Turk",
  "America/Grenada",
  "America/Guadeloupe",
  "America/Guatemala",
  "America/Guayaquil",
  "America/Guyana",
  "America/Halifax",
  "America/Havana",
  "America/Hermosillo",
  "America/Indiana/Indianapolis",
  "America/Indiana/Knox",
  "America/Indiana/Marengo",
  "America/Indiana/Petersburg",
  "America/Indiana/Tell_City",
  "America/Indiana/Vevay",
  "America/Indiana/Vincennes",
  "America/Indiana/Winamac",
  "America/Indianapolis",
  "America/Inuvik",
  "America/Iqaluit",
  "America/Jamaica",
  "America/Jujuy",
  "America/Juneau",
  "America/Kentucky/Louisville",
  "America/Kentucky/Monticello",
  "America/Knox_IN",
  "America/Kralendijk",
  "America/La_Paz",
  "America/Lima",
  "America/Los_Angeles",
  "America/Louisville",
  "America/Lower_Princes",
  "America/Maceio",
  "America/Managua",
  "America/Manaus",
  "America/Marigot",
  "America/Martinique",
  "America/Matamoros",
  "America/Mazatlan",
  "America/Mendoza",
  "America/Menominee",
  "America/Merida",
  "America/Metlakatla",
  "America/Mexico_City",
  "America/Miquelon",
  "America/Moncton",
  "America/Monterrey",
  "America/Montevideo",
  "America/Montreal",
  "America/Montserrat",
  "America/Nassau",
  "America/New_York",
  "America/Nipigon",
  "America/Nome",
  "America/Noronha",
  "America/North_Dakota/Beulah",
  "America/North_Dakota/Center",
  "America/North_Dakota/New_Salem",
  "America/Ojinaga",
  "America/Panama",
  "America/Pangnirtung",
  "America/Paramaribo",
  "America/Phoenix",
  "America/Port-au-Prince",
  "America/Port_of_Spain",
  "America/Porto_Acre",
  "America/Porto_Velho",
  "America/Puerto_Rico",
  "America/Rainy_River",
  "America/Rankin_Inlet",
  "America/Recife",
  "America/Regina",
  "America/Resolute",
  "America/Rio_Branco",
  "America/Rosario",
  "America/Santa_Isabel",
  "America/Santarem",
  "America/Santiago",
  "America/Santo_Domingo",
  "America/Sao_Paulo",
  "America/Scoresbysund",
  "America/Shiprock",
  "America/Sitka",
  "America/St_Barthelemy",
  "America/St_Johns",
  "America/St_Kitts",
  "America/St_Lucia",
  "America/St_Thomas",
  "America/St_Vincent",
  "America/Swift_Current",
  "America/Tegucigalpa",
  "America/Thule",
  "America/Thunder_Bay",
  "America/Tijuana",
  "America/Toronto",
  "America/Tortola",
  "America/Vancouver",
  "America/Virgin",
  "America/Whitehorse",
  "America/Winnipeg",
  "America/Yakutat",
  "America/Yellowknife",
  "Antarctica/Casey",
  "Antarctica/Davis",
  "Antarctica/DumontDUrville",
  "Antarctica/Macquarie",
  "Antarctica/Mawson",
  "Antarctica/McMurdo",
  "Antarctica/Palmer",
  "Antarctica/Rothera",
  "Antarctica/South_Pole",
  "Antarctica/Syowa",
  "Antarctica/Troll",
  "Antarctica/Vostok",
  "Arctic/Longyearbyen",
  "Asia/Aden",
  "Asia/Almaty",
  "Asia/Amman",
  "Asia/Anadyr",
  "Asia/Aqtau",
  "Asia/Aqtobe",
  "Asia/Ashgabat",
  "Asia/Ashkhabad",
  "Asia/Atyrau",
  "Asia/Baghdad",
  "Asia/Bahrain",
  "Asia/Baku",
  "Asia/Bangkok",
  "Asia/Barnaul",
  "Asia/Beirut",
  "Asia/Bishkek",
  "Asia/Brunei",
  "Asia/Calcutta",
  "Asia/Chita",
  "Asia/Choibalsan",
  "Asia/Chongqing",
  "Asia/Chungking",
  "Asia/Colombo",
  "Asia/Dacca",
  "Asia/Damascus",
  "Asia/Dhaka",
  "Asia/Dili",
  "Asia/Dubai",
  "Asia/Dushanbe",
  "Asia/Famagusta",
  "Asia/Gaza",
  "Asia/Harbin",
  "Asia/Hebron",
  "Asia/Ho_Chi_Minh",
  "Asia/Hong_Kong",
  "Asia/Hovd",
  "Asia/Irkutsk",
  "Asia/Istanbul",
  "Asia/Jakarta",
  "Asia/Jayapura",
  "Asia/Jerusalem",
  "Asia/Kabul",
  "Asia/Kamchatka",
  "Asia/Karachi",
  "Asia/Kashgar",
  "Asia/Kathmandu",
  "Asia/Katmandu",
  "Asia/Khandyga",
  "Asia/Kolkata",
  "Asia/Krasnoyarsk",
  "Asia/Kuala_Lumpur",
  "Asia/Kuching",
  "Asia/Kuwait",
  "Asia/Macao",
  "Asia/Macau",
  "Asia/Magadan",
  "Asia/Makassar",
  "Asia/Manila",
  "Asia/Muscat",
  "Asia/Nicosia",
  "Asia/Novokuznetsk",
  "Asia/Novosibirsk",
  "Asia/Omsk",
  "Asia/Oral",
  "Asia/Phnom_Penh",
  "Asia/Pontianak",
  "Asia/Pyongyang",
  "Asia/Qatar",
  "Asia/Qyzylorda",
  "Asia/Rangoon",
  "Asia/Riyadh",
  "Asia/Saigon",
  "Asia/Sakhalin",
  "Asia/Samarkand",
  "Asia/Seoul",
  "Asia/Shanghai",
  "Asia/Singapore",
  "Asia/Srednekolymsk",
  "Asia/Taipei",
  "Asia/Tashkent",
  "Asia/Tbilisi",
  "Asia/Tehran",
  "Asia/Tel_Aviv",
  "Asia/Thimbu",
  "Asia/Thimphu",
  "Asia/Tokyo",
  "Asia/Tomsk",
  "Asia/Ujung_Pandang",
  "Asia/Ulaanbaatar",
  "Asia/Ulan_Bator",
  "Asia/Urumqi",
  "Asia/Ust-Nera",
  "Asia/Vientiane",
  "Asia/Vladivostok",
  "Asia/Yakutsk",
  "Asia/Yangon",
  "Asia/Yekaterinburg",
  "Asia/Yerevan",
  "Atlantic/Azores",
  "Atlantic/Bermuda",
  "Atlantic/Canary",
  "Atlantic/Cape_Verde",
  "Atlantic/Faeroe",
  "Atlantic/Faroe",
  "Atlantic/Jan_Mayen",
  "Atlantic/Madeira",
  "Atlantic/Reykjavik",
  "Atlantic/South_Georgia",
  "Atlantic/St_Helena",
  "Atlantic/Stanley",
  "Australia/ACT",
  "Australia/Adelaide",
  "Australia/Brisbane",
  "Australia/Broken_Hill",
  "Australia/Canberra",
  "Australia/Currie",
  "Australia/Darwin",
  "Australia/Eucla",
  "Australia/Hobart",
  "Australia/LHI",
  "Australia/Lindeman",
  "Australia/Lord_Howe",
  "Australia/Melbourne",
  "Australia/North",
  "Australia/NSW",
  "Australia/Perth",
  "Australia/Queensland",
  "Australia/South",
  "Australia/Sydney",
  "Australia/Tasmania",
  "Australia/Victoria",
  "Australia/West",
  "Australia/Yancowinna",
  "Brazil/Acre",
  "Brazil/DeNoronha",
  "Brazil/East",
  "Brazil/West",
  "Canada/Atlantic",
  "Canada/Central",
  "Canada/Eastern",
  "Canada/Mountain",
  "Canada/Newfoundland",
  "Canada/Pacific",
  "Canada/Saskatchewan",
  "Canada/Yukon",
  "CET",
  "Chile/Continental",
  "Chile/EasterIsland",
  "CST6CDT",
  "Cuba",
  "EET",
  " Egypt",
  "Eire",
  "EST",
  "EST5EDT",
  "Etc/GMT",
  "Etc/GMT-0",
  "Etc/GMT-1",
  "Etc/GMT-10",
  "Etc/GMT-11",
  "Etc/GMT-12",
  "Etc/GMT-13",
  "Etc/GMT-14",
  "Etc/GMT-2",
  "Etc/GMT-3",
  "Etc/GMT-4",
  "Etc/GMT-5",
  "Etc/GMT-6",
  "Etc/GMT-7",
  "Etc/GMT-8",
  "Etc/GMT-9",
  "Etc/GMT+0",
  "Etc/GMT+1",
  "Etc/GMT+10",
  "Etc/GMT+11",
  "Etc/GMT+12",
  "Etc/GMT+2",
  "Etc/GMT+3",
  "Etc/GMT+4",
  "Etc/GMT+5",
  "Etc/GMT+6",
  "Etc/GMT+7",
  "Etc/GMT+8",
  "Etc/GMT+9",
  "Etc/GMT0",
  "Etc/Greenwich",
  "Etc/UCT",
  "Etc/Universal",
  "Etc/UTC",
  "Etc/Zulu",
  "Europe/Amsterdam",
  "Europe/Andorra",
  "Europe/Astrakhan",
  "Europe/Athens",
  "Europe/Belfast",
  "Europe/Belgrade",
  "Europe/Berlin",
  "Europe/Bratislava",
  "Europe/Brussels",
  "Europe/Bucharest",
  "Europe/Budapest",
  "Europe/Busingen",
  "Europe/Chisinau",
  "Europe/Copenhagen",
  "Europe/Dublin",
  "Europe/Gibraltar",
  "Europe/Guernsey",
  "Europe/Helsinki",
  "Europe/Isle_of_Man",
  "Europe/Istanbul",
  "Europe/Jersey",
  "Europe/Kaliningrad",
  "Europe/Kiev",
  "Europe/Kirov",
  "Europe/Lisbon",
  "Europe/Ljubljana",
  "Europe/London",
  "Europe/Luxembourg",
  "Europe/Madrid",
  "Europe/Malta",
  "Europe/Mariehamn",
  "Europe/Minsk",
  "Europe/Monaco",
  "Europe/Moscow",
  "Europe/Nicosia",
  "Europe/Oslo",
  "Europe/Paris",
  "Europe/Podgorica",
  "Europe/Prague",
  "Europe/Riga",
  "Europe/Rome",
  "Europe/Samara",
  "Europe/San_Marino",
  "Europe/Sarajevo",
  "Europe/Saratov",
  "Europe/Simferopol",
  "Europe/Skopje",
  "Europe/Sofia",
  "Europe/Stockholm",
  "Europe/Tallinn",
  "Europe/Tirane",
  "Europe/Tiraspol",
  "Europe/Ulyanovsk",
  "Europe/Uzhgorod",
  "Europe/Vaduz",
  "Europe/Vatican",
  "Europe/Vienna",
  "Europe/Vilnius",
  "Europe/Volgograd",
  "Europe/Warsaw",
  "Europe/Zagreb",
  "Europe/Zaporozhye",
  "Europe/Zurich",
  "Factory",
  "GB",
  " GB-Eire",
  "GMT",
  "GMT-0",
  "GMT+0",
  "GMT0",
  "Greenwich",
  "Hongkong",
  "HST",
  "Iceland",
  "Indian/Antananarivo",
  "Indian/Chagos",
  "Indian/Christmas",
  "Indian/Cocos",
  "Indian/Comoro",
  "Indian/Kerguelen",
  "Indian/Mahe",
  "Indian/Maldives",
  "Indian/Mauritius",
  "Indian/Mayotte",
  "Indian/Reunion",
  "Iran",
  "Israel",
  " Jamaica",
  "Japan",
  "Kwajalein",
  " Libya",
  "MET",
  "Mexico/BajaNorte",
  "Mexico/BajaSur",
  "Mexico/General",
  "MST",
  "MST7MDT",
  "Navajo",
  " NZ",
  "NZ-CHAT",
  "Pacific/Apia",
  "Pacific/Auckland",
  "Pacific/Bougainville",
  "Pacific/Chatham",
  "Pacific/Chuuk",
  "Pacific/Easter",
  "Pacific/Efate",
  "Pacific/Enderbury",
  "Pacific/Fakaofo",
  "Pacific/Fiji",
  "Pacific/Funafuti",
  "Pacific/Galapagos",
  "Pacific/Gambier",
  "Pacific/Guadalcanal",
  "Pacific/Guam",
  "Pacific/Honolulu",
  "Pacific/Johnston",
  "Pacific/Kiritimati",
  "Pacific/Kosrae",
  "Pacific/Kwajalein",
  "Pacific/Majuro",
  "Pacific/Marquesas",
  "Pacific/Midway",
  "Pacific/Nauru",
  "Pacific/Niue",
  "Pacific/Norfolk",
  "Pacific/Noumea",
  "Pacific/Pago_Pago",
  "Pacific/Palau",
  "Pacific/Pitcairn",
  "Pacific/Pohnpei",
  "Pacific/Ponape",
  "Pacific/Port_Moresby",
  "Pacific/Rarotonga",
  "Pacific/Saipan",
  "Pacific/Samoa",
  "Pacific/Tahiti",
  "Pacific/Tarawa",
  "Pacific/Tongatapu",
  "Pacific/Truk",
  "Pacific/Wake",
  "Pacific/Wallis",
  "Pacific/Yap",
  "Poland",
  "Portugal",
  "PRC",
  "PST8PDT",
  "ROC",
  "ROK",
  "Singapore",
  "Turkey",
  "UCT",
  "Universal",
  "US/Alaska",
  "US/Aleutian",
  "US/Arizona",
  "US/Central",
  "US/East-Indiana",
  "US/Eastern",
  "US/Hawaii",
  "US/Indiana-Starke",
  "US/Michigan",
  "US/Mountain",
  "US/Pacific",
  "US/Samoa",
  "UTC",
  "W-SU",
  "WET",
  " Zulu",
];

export const currencyCodeOptions: { label: string; value: string }[] = [
  {
    label: "Algerian Dinar (DZD)",
    value: "DZD",
  },
  {
    label: "Argentine Peso (ARS)",
    value: "ARS",
  },
  {
    label: "Australian Dollar (AUD)",
    value: "AUD",
  },
  {
    label: "Bangladeshi Taka (BDT)",
    value: "BDT",
  },
  {
    label: "Bolivian Boliviano (BOB)",
    value: "BOB",
  },
  {
    label: "Brazilian Real (BRL)",
    value: "BRL",
  },
  {
    label: "British Pound (GBP)",
    value: "GBP",
  },
  {
    label: "Canadian Dollar (CAD)",
    value: "CAD",
  },
  {
    label: "Chilean Peso (CLP)",
    value: "CLP",
  },
  {
    label: "Chinese Yuan (CNY)",
    value: "CNY",
  },
  {
    label: "Colombian Peso (COP)",
    value: "COP",
  },
  {
    label: "Costa Rican Colon (CRC)",
    value: "CRC",
  },
  {
    label: "Czech Koruna (CZK)",
    value: "CZK",
  },
  {
    label: "Danish Krone (DKK)",
    value: "DKK",
  },
  {
    label: "Egyptian Pounds (EGP)",
    value: "EGP",
  },
  {
    label: "Euro (EUR)",
    value: "EUR",
  },
  {
    label: "Guatemalan Quetza (GTQ)",
    value: "GTQ",
  },
  {
    label: "Honduran Lempira (HNL)",
    value: "HNL",
  },
  {
    label: "Hong Kong Dollar (HKD)",
    value: "HKD",
  },
  {
    label: "Hungarian Forint (HUF)",
    value: "HUF",
  },
  {
    label: "Iceland Krona (ISK)",
    value: "ISK",
  },
  {
    label: "Indian Rupee (INR)",
    value: "INR",
  },
  {
    label: "Indonesian Rupiah (IDR)",
    value: "IDR",
  },
  {
    label: "Israeli New Shekel (ILS)",
    value: "ILS",
  },
  {
    label: "Japanese Yen (JPY)",
    value: "JPY",
  },
  {
    label: "Kenyan Shilling (KES)",
    value: "KES",
  },
  {
    label: "Korean Won (KRW)",
    value: "KRW",
  },
  {
    label: "Macau Patacas (MOP)",
    value: "MOP",
  },
  {
    label: "Malaysian Ringgit (MYR)",
    value: "MYR",
  },
  {
    label: "Mexican Peso (MXN)",
    value: "MXN",
  },
  {
    label: "New Zealand Dollar (NZD)",
    value: "NZD",
  },
  {
    label: "Nicaraguan Cordoba (NIO)",
    value: "NIO",
  },
  {
    label: "Nigerian Naira (NGN)",
    value: "NGN",
  },
  {
    label: "Norwegian Krone (NOK)",
    value: "NOK",
  },
  {
    label: "Pakistani Rupee (PKR)",
    value: "PKR",
  },
  {
    label: "Paraguayan Guarani (PYG)",
    value: "PYG",
  },
  {
    label: "Peruvian Nuevo Sol (PEN)",
    value: "PEN",
  },
  {
    label: "Philippine Peso (PHP)",
    value: "PHP",
  },
  {
    label: "Polish Zloty (PLN)",
    value: "PLN",
  },
  {
    label: "Qatari Rials (QAR)",
    value: "QAR",
  },
  {
    label: "Romanian Leu (RON)",
    value: "RON",
  },
  {
    label: "Russian Ruble (RUB)",
    value: "RUB",
  },
  {
    label: "Saudi Arabian Riyal (SAR)",
    value: "SAR",
  },
  {
    label: "Singapore Dollar (SGD)",
    value: "SGD",
  },
  {
    label: "South African Rand (ZAR)",
    value: "ZAR",
  },
  {
    label: "Sri Lankan Rupee (LKR)",
    value: "LKR",
  },
  {
    label: "Swedish Krona (SEK)",
    value: "SEK",
  },
  {
    label: "Swiss Franc (CHF)",
    value: "CHF",
  },
  {
    label: "Taiwan Dollar (TWD)",
    value: "TWD",
  },
  {
    label: "Thai Baht (THB)",
    value: "THB",
  },
  {
    label: "Turkish Lira (TRY)",
    value: "TRY",
  },
  {
    label: "Uae Dirham (AED)",
    value: "AED",
  },
  {
    label: "United States Dollar (USD)",
    value: "USD",
  },
  {
    label: "Uruguay Peso (UYU)",
    value: "UYU",
  },
  {
    label: "Venezuelan Bolivar (VEF)",
    value: "VEF",
  },
  {
    label: "Vietnamese Dong (VND)",
    value: "VND",
  },
];
